### ISSUE TITLE
Simulator prevents the use of Groundwork at low durability even with Trained Perfection active

### ISSUE THREAD

**Issue by KonaeAkira** [alostsock/craftingway#27]
![image](https://github.com/alostsock/craftingway/assets/31180380/f6745405-490b-4332-b424-00e9b1f123cd)

Actions 1-4 are only used to get durability down to 10.

**Comment by alostsock** [comment]
In a sleep deprived haze I think I misread that Trained Perfection's effect applied to CP and not durability, I think that if this works the same way as Waste Not does, it should allow un-downgraded Groundwork in this case

https://github.com/alostsock/crafty/commit/583e50d8c3ce8f9bc58389a01a24e527c6e5303f
https://github.com/alostsock/craftingway/commit/13df244f6254ebba89f82fa39d9cb1c6560b660a
