### ISSUE TITLE
Issue: Pasting the macro only pastes first line

### ISSUE THREAD

**Issue by mindofbeholder** [alostsock/craftingway#3]
When I copy a macro from craftingway and paste it into ffxiv, it only pastes the first line.
When I paste the macro into a note doc and copy it again it pastes the entire macro.

**Comment by mindofbeholder** [comment]
https://imgur.com/a/JwMQ7AU

**Comment by alostsock** [comment]
Should be fixed now via https://github.com/alostsock/craftingway/commit/742b40ab7823469d10ba2b43f521a998dc312466.

**Comment by mindofbeholder** [comment]
Confirmed fixed! Thanks for your quick turnaround.
