### ISSUE TITLE
Trained Perfection is lost when using actions that don't use it

### ISSUE THREAD

**Issue by Alfaksan** [alostsock/craftingway#32]
Start any craft, craft manually and do the following sequence:
Muscle Memory > Trained Perfection >Veneration > Groundwork

In game you will spend only 10 durability, in app you spend 30.
![image](https://github.com/user-attachments/assets/a926b7a3-9a9e-4620-8729-ad93add13868)

**Comment by alostsock** [comment]
Sorry for the delay! This should be fixed -- I was an idiot and forgot to update the site to match the preview branch.
