### ISSUE TITLE
Feature Request: Checkbox for "Accept 100% HQ Solutions Only"

### ISSUE THREAD

**Issue by minorpains** [alostsock/craftingway#33]
Many times when solving a craft, I find the given solution doesn't give 100% HQ, but then just by adjusting step limit it will find a solution with 100% HQ but in the same number of steps as the first solution which is typically in less steps than the limit given. Requesting adding the feature of a checkbox to "Accept 100% HQ Solutions Only" so that the search continues until 100% HQ is achieved as well as successful craft.

Example that shows 2 15 step solutions, 1 with 100% HQ, and 1 without:
LTW Lvl 94
Craftmanship: 3958
Control: 3897
CP: 601
Recipe: Gomphotherium Leather

Step Limit: 16
Gives 15 step solution with 10110/10200 Quality

Step Limit: 18 (no other changes)
Gives 15 step solution with 10229/10200 Quality

**Comment by alostsock** [comment]
Unfortunately I think this would be pretty difficult to do without a major rewrite of certain parts of the solver. I may revisit this in the future, but for now I'm closing this as "won't do", sorry!
