### ISSUE TITLE
Feature Request: Account for HQ Ingredients

### ISSUE THREAD

**Issue by mindofbeholder** [alostsock/craftingway#4]
Can you allow us to select which components in a recipe are HQ to increase the base quality of the recipe before solving?

I understand that this will likely require a large addition to the codebase if it's to be supported.

**Comment by mindofbeholder** [comment]
A likely more simple alternative would be to allow us to select the "starting" quality and we can do our own math for the HQ ingredients.

**Comment by alostsock** [comment]
> A likely more simple alternative would be to allow us to select the "starting" quality and we can do our own math for the HQ ingredients.

This is the plan once I get around to it, and it should be simple to add.

I've considered doing the "pick HQ ingredients" thing but IMO the benefit-to-work ratio is not great, as you've guessed. If I do add it, it'll be in the far future.

**Comment by alostsock** [comment]
Giving it some more thought, I'm going to try adding the ability to HQ specific ingredients. With recipe ingredient data it opens up the possibility of adding features like [this](https://www.reddit.com/r/ffxiv/comments/12pg6n1/ive_made_a_website_craftingwayapp_a_crafting/jgobvqz/), but that'll be a ways away.

Still not sure where exactly to put this "ingredient selection" in the UI. For desktop, I can probably reduce the width of the progress bars and put some ingredient sliders to the side of them, but that would make the mobile view a lot less compact. The solution will probably have to be some kind of expandable section, I guess.

**Comment by mindofbeholder** [comment]
That sort of feels wildly out of scope for a crafting solver tool. I see craftingway as a companion tool to things like ffxivteamcraft or garland instead of a replacement.

Would you consider backlogging/second phasing that type of behavior and instead focus on just adding a starting quality value? I feel like this would generate more value for less work.

**Comment by alostsock** [comment]
Lol thanks for keeping me sane. Good points, I'll do that first.

**Comment by alostsock** [comment]
HQ ingredients are in!
